### ISSUE TITLE
Mockups aanmaken

### ISSUE THREAD

**Issue by BramSikkens** [SoftwareProject2-groep6/Web-Applicatie#4]
Mockup maken van de webapplicatie 

- Niet te gedetailleerd
- Probeer consistent te zijn

**Comment by BramSikkens** [comment]
![homepage](https://user-images.githubusercontent.com/16198438/31320345-58e8770c-ac73-11e7-8d4c-4a91ce294205.png)


Eerste mockup van @fonsambroos

**Comment by fonsambroos** [comment]
![homepage](https://user-images.githubusercontent.com/32596503/31575968-f2ee0740-b0f1-11e7-91a3-555c52e42bb2.png)
![inschrijven](https://user-images.githubusercontent.com/32596503/31575969-f5800918-b0f1-11e7-91be-ba582247a543.png)
![boeken](https://user-images.githubusercontent.com/32596503/31575971-f9fbc630-b0f1-11e7-9578-70496ba92169.png)

Mockup van website, deze is nog zeer basic maar is bedoelt om de algemene structuur aan het licht te brengen. De verwijziginen uitschrijven, inschrijven en bestellen zullen een nieuwe pagina openen.
